# app/ai/memory_engine.py
"""
Memory Engine for Zylos
- Short-term: conversation-level ephemeral storage (fast, non-persistent)
- Mid-term: per-user rolling summaries (persisted)
- Long-term: per-user knowledge items (persisted + vectorized)
- Knowledge Graph: simple adjacency store for relations (persisted)
- Integrations: uses rag_engine.vector_store for embeddings (if available)
- Exposes helper functions used by brain.py:
    - get_relevant_memory(user_id, query, k=5) -> List[str]
        - add_memory_item(user_id, user_text, assistant_text, metadata=None)
            - add_short_memory(conversation_id, item)
                - retrieve_short(conversation_id)
                    - summarize_user_memory(user_id)
                        - cleanup_aged_memory(age_days)
                        """

                        import json
                        import threading
                        import time
                        import os
                        from datetime import datetime, timedelta
                        from typing import List, Dict, Any, Optional

                        from .rag_engine import search as rag_search, rank_candidates
                        from ..core.config import settings
                        from .summarizer import summarize_text

                        LOCK = threading.RLock()

                        DATA_DIR = "app/data"
                        LONG_PATH = os.path.join(DATA_DIR, "memory_long.json")
                        MID_PATH = os.path.join(DATA_DIR, "memory_mid.json")
                        KG_PATH = os.path.join(DATA_DIR, "memory_kg.json")

                        # In-memory short-term store
                        _short_memory: Dict[str, List[Dict[str, Any]]] = {}  # conv_id -> list[{text, ts, user_id}]
                        # Mid and long persisted caches (lazy-loaded)
                        _mid_cache: Dict[str, List[Dict[str, Any]]] = {}
                        _long_cache: Dict[str, List[Dict[str, Any]]] = {}
                        _kg: Dict[str, Dict[str, Any]] = {}  # node -> {relations: {rel: [targets]}, meta: {}}

                        # Ensure data dir
                        os.makedirs(DATA_DIR, exist_ok=True)

                        # Load persisted data at module import
                        def _load_json(path: str) -> Dict[str, Any]:
                            if os.path.exists(path):
                                    try:
                                                with open(path, "r", encoding="utf-8") as f:
                                                                return json.load(f)
                                                                        except Exception:
                                                                                    return {}
                                                                                        return {}

                                                                                        def _persist_json(path: str, obj: Dict[str, Any]) -> None:
                                                                                            tmp = path + ".tmp"
                                                                                                with open(tmp, "w", encoding="utf-8") as f:
                                                                                                        json.dump(obj, f, ensure_ascii=False, indent=2)
                                                                                                            os.replace(tmp, path)

                                                                                                            # Initialize caches
                                                                                                            _with_lock = LOCK
                                                                                                            with _with_lock:
                                                                                                                _mid_cache = _load_json(MID_PATH) or {}
                                                                                                                    _long_cache = _load_json(LONG_PATH) or {}
                                                                                                                        _kg = _load_json(KG_PATH) or {}

                                                                                                                        # Helper utilities
                                                                                                                        def _now_ts() -> str:
                                                                                                                            return datetime.utcnow().isoformat() + "Z"

                                                                                                                            def _persist_long():
                                                                                                                                with LOCK:
                                                                                                                                        _persist_json(LONG_PATH, _long_cache)

                                                                                                                                        def _persist_mid():
                                                                                                                                            with LOCK:
                                                                                                                                                    _persist_json(MID_PATH, _mid_cache)

                                                                                                                                                    def _persist_kg():
                                                                                                                                                        with LOCK:
                                                                                                                                                                _persist_json(KG_PATH, _kg)


                                                                                                                                                                # ---------------------------
                                                                                                                                                                # Short-term memory functions
                                                                                                                                                                # ---------------------------
                                                                                                                                                                def add_short_memory(conversation_id: str, item: Dict[str, Any]):
                                                                                                                                                                    """
                                                                                                                                                                        item: {"text": str, "user_id": str, "role": "user"|"assistant", "ts": optional}
                                                                                                                                                                            """
                                                                                                                                                                                with LOCK:
                                                                                                                                                                                        _short_memory.setdefault(conversation_id, []).append({
                                                                                                                                                                                                    "text": item.get("text"),
                                                                                                                                                                                                                "role": item.get("role", "user"),
                                                                                                                                                                                                                            "user_id": item.get("user_id"),
                                                                                                                                                                                                                                        "ts": item.get("ts", _now_ts())
                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                        # Keep short memory bounded (e.g., last 100 messages)
                                                                                                                                                                                                                                                                if len(_short_memory[conversation_id]) > 200:
                                                                                                                                                                                                                                                                            _short_memory[conversation_id] = _short_memory[conversation_id][-200:]


                                                                                                                                                                                                                                                                            def retrieve_short(conversation_id: str, limit: int = 50) -> List[Dict[str, Any]]:
                                                                                                                                                                                                                                                                                with LOCK:
                                                                                                                                                                                                                                                                                        lst = _short_memory.get(conversation_id, [])[-limit:]
                                                                                                                                                                                                                                                                                                return lst.copy()


                                                                                                                                                                                                                                                                                                # ---------------------------
                                                                                                                                                                                                                                                                                                # Mid-term memory functions
                                                                                                                                                                                                                                                                                                # ---------------------------
                                                                                                                                                                                                                                                                                                def add_mid_memory(user_id: str, summary: str, ts: Optional[str] = None):
                                                                                                                                                                                                                                                                                                    with LOCK:
                                                                                                                                                                                                                                                                                                            arr = _mid_cache.setdefault(user_id, [])
                                                                                                                                                                                                                                                                                                                    arr.append({"summary": summary, "ts": ts or _now_ts()})
                                                                                                                                                                                                                                                                                                                            # Keep mid memory reasonable length
                                                                                                                                                                                                                                                                                                                                    if len(arr) > 200:
                                                                                                                                                                                                                                                                                                                                                arr[:] = arr[-200:]
                                                                                                                                                                                                                                                                                                                                                        _persist_mid()


                                                                                                                                                                                                                                                                                                                                                        def get_mid_memory(user_id: str, limit: int = 10) -> List[str]:
                                                                                                                                                                                                                                                                                                                                                            with LOCK:
                                                                                                                                                                                                                                                                                                                                                                    arr = _mid_cache.get(user_id, [])[-limit:]
                                                                                                                                                                                                                                                                                                                                                                            return [a["summary"] for a in arr]


                                                                                                                                                                                                                                                                                                                                                                            # ---------------------------
                                                                                                                                                                                                                                                                                                                                                                            # Long-term memory functions
                                                                                                                                                                                                                                                                                                                                                                            # ---------------------------
                                                                                                                                                                                                                                                                                                                                                                            def add_long_memory(user_id: str, item: Dict[str, Any]):
                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                    item: {"type": str, "text": str, "meta": {...}, "ts": ISO}
                                                                                                                                                                                                                                                                                                                                                                                        Appends to user's long memory and persists. Also vectorizes if vector_store available.
                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                from app.database.vector_store import vector_store  # lazy import
                                                                                                                                                                                                                                                                                                                                                                                                    with LOCK:
                                                                                                                                                                                                                                                                                                                                                                                                            arr = _long_cache.setdefault(user_id, [])
                                                                                                                                                                                                                                                                                                                                                                                                                    entry = {
                                                                                                                                                                                                                                                                                                                                                                                                                                "id": f"mem_{int(time.time() * 1000)}",
                                                                                                                                                                                                                                                                                                                                                                                                                                            "type": item.get("type", "note"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "text": item.get("text"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "meta": item.get("meta", {}),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "ts": item.get("ts", _now_ts())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                arr.append(entry)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # persist
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _persist_long()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # add to vector store for retrieval
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if hasattr(vector_store, "add"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # add the text ctx, optionally include metadata
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            vector_store.add([entry["text"]])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ignore vector store errors
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return entry


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def get_long_memory(user_id: str, limit: int = 50) -> List[Dict[str, Any]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with LOCK:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return (_long_cache.get(user_id, [])[-limit:]).copy()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ---------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Knowledge Graph functions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ---------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def kg_add_relation(subject: str, relation: str, obj: str, meta: Optional[Dict[str, Any]] = None):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Add a directed relation subject -[relation]-> obj
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with LOCK:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        node = _kg.setdefault(subject, {"relations": {}, "meta": {}})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rels = node["relations"].setdefault(relation, [])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if obj not in rels:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rels.append(obj)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # store meta if provided
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if meta:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                node["meta"].update(meta)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        _persist_kg()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return True


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def kg_get_relations(subject: str) -> Dict[str, List[str]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with LOCK:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return _kg.get(subject, {}).get("relations", {}).copy()


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def kg_find_paths(start: str, depth: int = 2) -> List[List[str]]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Simple BFS to find short paths starting from start node (depth-limited).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Returns list of paths (list of node names).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                with LOCK:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        paths = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue = [[start]]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        while queue:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    path = queue.pop(0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if len(path) - 1 >= depth:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            last = path[-1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rels = _kg.get(last, {}).get("relations", {})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for rel, targets in rels.items():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for t in targets:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new_path = path + [t]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            paths.append(new_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                queue.append(new_path)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return paths


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # High-level helpers used by brain.py
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ---------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def add_memory_item(user_id: str, user_text: str, assistant_text: str, metadata: Optional[Dict[str, Any]] = None):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Called by brain after producing final reply.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Stores both user utterance and assistant reply into long memory (optionally).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Also updates mid-term summaries occasionally.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Save a long memory chunk for important events or every N interactions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    combined = f"User: {user_text}\nAssistant: {assistant_text}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        entry = add_long_memory(user_id, {"type": "dialog", "text": combined, "meta": metadata or {}})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Optionally update mid-term summary every X entries
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mid_list = _mid_cache.get(user_id, [])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if len(mid_list) % 5 == 0:  # every ~5 stored mid items, summarize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # create a short summary of last few entries
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        last_texts = [e["text"] for e in _long_cache.get(user_id, [])[-10:]]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if last_texts:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    s = summarize_text("\n\n".join(last_texts), max_tokens=150)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    add_mid_memory(user_id, s)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return entry


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def get_relevant_memory(user_id: str, query: str, k: int = 5) -> List[str]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        """
                                                                                                                                                                                                   